
INSERT INTO resources (user_id, title, description, url, category) VALUES
  (1, 'Introduction to SQL', 'A beginner-friendly SQL tutorial', 'https://www.sqltutorial.org/introduction-to-sql/', 'Video'),
  (2, 'Advanced SQL Techniques', 'Learn advanced SQL querying', 'https://www.sqlshack.com/advanced-sql-techniques/', 'Video'),
  (3, 'Getting Started with Python', 'Python programming basics', 'https://realpython.com/start-here/', 'Video'),
  (4, 'Web Development Tutorial', 'Build a basic website from scratch', 'https://developer.mozilla.org/en-US/docs/Learn', 'Video'),
  (5, 'Introduction to Machine Learning', 'Overview of machine learning concepts', 'https://machinelearningmastery.com/what-is-machine-learning/', 'Video'),
  (6, 'Digital Art: Creating Stunning Graphics', 'Learn digital art techniques using software', 'https://www.digitalartsonline.co.uk/features/illustration/digital-art-tips-creative-coding/', 'Video'),
  (7, 'Cooking Adventures: Recipes and Stories', 'Exploring the world of cooking', 'https://www.bonappetit.com/', 'Blog'),
  (8, 'Travel Tales: Exploring New Horizons', 'Travel stories and recommendations', 'https://www.nomadicmatt.com/', 'Blog'),
  (9, 'Fitness Journey: Workouts and Wellness', 'Stay fit and healthy with effective workouts', 'https://www.self.com/fitness', 'Blog'),
  (10, 'Fashion Trends: Style Inspiration', 'Stay updated with the latest fashion trends', 'https://www.vogue.com/', 'Blog'),
  (11, 'Introduction to Astronomy', 'Discover the wonders of the universe', 'https://www.space.com/astronomy-basics', 'Science'),
  (12, 'The Science of Climate Change', 'Understanding climate science and its impact', 'https://www.nationalgeographic.com/environment/global-warming/deforestation/', 'Science'),
  (13, 'Coding and Development News', 'Stay informed about the latest programming trends', 'https://www.codinghorror.com/blog/', 'Technology'),
  (14, 'Artificial Intelligence Explained', 'Learn about AI and its applications', 'https://www.sas.com/en_us/insights/analytics/what-is-artificial-intelligence.html', 'Technology'),
  (15, 'Introduction to Meditation', 'Learn techniques for mindful meditation', 'https://www.mindful.org/how-to-meditate/', 'Wellness'),
  (16, 'Healthy Recipes: Nutritious Meals', 'Cook delicious and balanced meals', 'https://www.eatingwell.com/', 'Wellness'),
  (17, 'Mindful Living: Stress Management', 'Tips for reducing stress and improving well-being', 'https://www.mindbodygreen.com/0-13914/9-essential-habits-for-a-happy-mind.html', 'Wellness'),
  (18, 'Parenting Tips and Advice', 'Guidance for effective parenting and child development', 'https://www.verywellfamily.com/parenting-4157077', 'Lifestyle'),
  (19, 'Art Appreciation: Famous Paintings', 'Explore iconic artworks from history', 'https://www.nationalgallery.org.uk/paintings', 'Art'),
  (20, 'Literature Corner: Book Reviews', 'Discover new books and literary recommendations', 'https://www.goodreads.com/', 'Art'),
  (21, 'Film Critiques and Movie News', 'Stay updated with the latest movie releases and reviews', 'https://www.rottentomatoes.com/', 'Art'),
  (22, 'Music Exploration: Genres and Artists', 'Discover diverse music genres and artists', 'https://www.billboard.com/', 'Art'),
  (23, 'Language Learning: Spanish Basics', 'Get started with basic Spanish phrases', 'https://www.duolingo.com/course/es/en/Learn-Spanish', 'Language'),
  (24, 'French Language Essentials', 'Learn essential French phrases and vocabulary', 'https://www.fluentu.com/en/blog/french/french-vocabulary/', 'Language'),
  (25, 'Japanese Language for Beginners', 'Start learning Japanese for communication and travel', 'https://www.tofugu.com/learn-japanese/', 'Language'),
  (26, 'German Language Resources', 'Explore German language resources and lessons', 'https://www.dw.com/en/learn-german/s-2469', 'Language');

